# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - shellscript/*

pool:
  name: Default

steps:
- bash: sh shellscript/helloWorld.sh
  displayName: 'Run a one-line script'
