apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: docker
    image: docker:dind  # Docker-in-Docker image
    args:
      - --host tcp://0.0.0.0:2375
    securityContext:
      privileged: true  # Required for running Docker inside Docker
    volumeMounts:
      - name: docker-data
        mountPath: /var/lib/docker
  - image: "ubuntu:latest"
    name: "jnlp"
    command:
      - sleep 300000
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
    env:
    - name: "DOCKER_HOST"
      value: "tcp://127.0.0.1:2375"
  volumes:
  - name: docker-data
    emptyDir: {}
  restartPolicy: "Never"