apiVersion: v1
kind: Pod
metadata:
  name: test1
spec:
  containers:
  - name: docker
    image: docker:dind  # Docker-in-Docker image
    command: ["dockerd", "--tls=false", "--host=unix:///var/run/docker.sock", "--host=tcp://localhost:2375"]
    securityContext:
      privileged: true  # Required for running Docker inside Docker
    volumeMounts:
      - name: docker-data
        mountPath: /var/lib/docker
  - image: "043196765225.dkr.ecr.us-east-1.amazonaws.com/jenkins-test:latest"
    name: "jnlp"
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
    env:
    - name: "DOCKER_HOST"
      value: "tcp://localhost:2375"
  volumes:
  - name: docker-data
    emptyDir: {}
  restartPolicy: "Never"