#FROM ubuntu

#CMD echo "CMD:Hello World"

#ENTRYPOINT echo "Hello World"

#CMD echo "CMD:Hello World"

#ENTRYPOINT ["echo", "Hello World"]

#CMD echo "CMD:Hello World"
#CMD ["echo", "CMD:Hello World"]a

FROM ubuntu

COPY images.html /tmp
