# Stage 1: Use jenkins/inbound-agent as the base image
FROM jenkins/inbound-agent:3107.v665000b_51092-15 as jenkins-agent

# Stage 2: Create the final image
FROM jenkins-agent

# Switch to root user
USER root

# Install Docker
RUN curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh

# Optionally, you can install additional tools or dependencies here if needed
# For example, you can add curl, git, or other utilities
# RUN apk --no-cache add curl git

USER jenkins